package cpdlc

// Uplink message labels (ground to air).
// These are ATC instructions/requests to the aircraft.
var uplinkLabels = map[int]string{
	0:   "UNABLE",
	1:   "STANDBY",
	2:   "REQUEST DEFERRED",
	3:   "ROGER",
	4:   "AFFIRM",
	5:   "NEGATIVE",
	6:   "EXPECT [altitude]",
	7:   "EXPECT CLIMB AT [time]",
	8:   "EXPECT CLIMB AT [position]",
	9:   "EXPECT DESCENT AT [time]",
	10:  "EXPECT DESCENT AT [position]",
	11:  "EXPECT CRUISE CLIMB AT [time]",
	12:  "EXPECT CRUISE CLIMB AT [position]",
	13:  "AT [time] EXPECT CLIMB TO [altitude]",
	14:  "AT [position] EXPECT CLIMB TO [altitude]",
	15:  "AT [time] EXPECT DESCENT TO [altitude]",
	16:  "AT [position] EXPECT DESCENT TO [altitude]",
	17:  "AT [time] EXPECT CRUISE CLIMB TO [altitude]",
	18:  "AT [position] EXPECT CRUISE CLIMB TO [altitude]",
	19:  "MAINTAIN [altitude]",
	20:  "CLIMB TO AND MAINTAIN [altitude]",
	21:  "AT [time] CLIMB TO AND MAINTAIN [altitude]",
	22:  "AT [position] CLIMB TO AND MAINTAIN [altitude]",
	23:  "DESCEND TO AND MAINTAIN [altitude]",
	24:  "AT [time] DESCEND TO AND MAINTAIN [altitude]",
	25:  "AT [position] DESCEND TO AND MAINTAIN [altitude]",
	26:  "CLIMB TO REACH [altitude] BY [time]",
	27:  "CLIMB TO REACH [altitude] BY [position]",
	28:  "DESCEND TO REACH [altitude] BY [time]",
	29:  "DESCEND TO REACH [altitude] BY [position]",
	30:  "MAINTAIN BLOCK [altitude] TO [altitude]",
	31:  "CLIMB TO AND MAINTAIN BLOCK [altitude] TO [altitude]",
	32:  "DESCEND TO AND MAINTAIN BLOCK [altitude] TO [altitude]",
	33:  "CRUISE [altitude]",
	34:  "CRUISE CLIMB TO [altitude]",
	35:  "CRUISE CLIMB ABOVE [altitude]",
	36:  "EXPEDITE CLIMB TO [altitude]",
	37:  "EXPEDITE DESCENT TO [altitude]",
	38:  "IMMEDIATELY CLIMB TO [altitude]",
	39:  "IMMEDIATELY DESCEND TO [altitude]",
	40:  "IMMEDIATELY STOP CLIMB AT [altitude]",
	41:  "IMMEDIATELY STOP DESCENT AT [altitude]",
	42:  "EXPECT TO CROSS [position] AT [altitude]",
	43:  "EXPECT TO CROSS [position] AT OR ABOVE [altitude]",
	44:  "EXPECT TO CROSS [position] AT OR BELOW [altitude]",
	45:  "EXPECT TO CROSS [position] AT AND MAINTAIN [altitude]",
	46:  "CROSS [position] AT [altitude]",
	47:  "CROSS [position] AT OR ABOVE [altitude]",
	48:  "CROSS [position] AT OR BELOW [altitude]",
	49:  "CROSS [position] AT AND MAINTAIN [altitude]",
	50:  "CROSS [position] BETWEEN [altitude] AND [altitude]",
	51:  "CROSS [position] AT [time]",
	52:  "CROSS [position] AT OR BEFORE [time]",
	53:  "CROSS [position] AT OR AFTER [time]",
	54:  "CROSS [position] BETWEEN [time] AND [time]",
	55:  "CROSS [position] AT [speed]",
	56:  "CROSS [position] AT OR LESS THAN [speed]",
	57:  "CROSS [position] AT OR GREATER THAN [speed]",
	58:  "CROSS [position] AT [time] AT [altitude]",
	59:  "CROSS [position] AT OR BEFORE [time] AT [altitude]",
	60:  "CROSS [position] AT OR AFTER [time] AT [altitude]",
	61:  "CROSS [position] AT AND MAINTAIN [altitude] AT [speed]",
	62:  "AT [time] CROSS [position] AT AND MAINTAIN [altitude]",
	63:  "AT [time] CROSS [position] AT AND MAINTAIN [altitude] AT [speed]",
	64:  "OFFSET [distanceoffset] [direction] OF ROUTE",
	65:  "AT [position] OFFSET [distanceoffset] [direction] OF ROUTE",
	66:  "AT [time] OFFSET [distanceoffset] [direction] OF ROUTE",
	67:  "PROCEED BACK ON ROUTE",
	68:  "REJOIN ROUTE BY [position]",
	69:  "REJOIN ROUTE BY [time]",
	70:  "EXPECT BACK ON ROUTE BY [position]",
	71:  "EXPECT BACK ON ROUTE BY [time]",
	72:  "RESUME OWN NAVIGATION",
	73:  "[predepartureclearance]",
	74:  "PROCEED DIRECT TO [position]",
	75:  "WHEN ABLE PROCEED DIRECT TO [position]",
	76:  "AT [time] PROCEED DIRECT TO [position]",
	77:  "AT [position] PROCEED DIRECT TO [position]",
	78:  "AT [altitude] PROCEED DIRECT TO [position]",
	79:  "CLEARED TO [position] VIA [routeclearance]",
	80:  "CLEARED [routeclearance]",
	81:  "CLEARED [procedurename]",
	82:  "CLEARED TO DEVIATE UP TO [distanceoffset] [direction] OF ROUTE",
	83:  "AT [position] CLEARED [routeclearance]",
	84:  "AT [position] CLEARED [procedurename]",
	85:  "EXPECT [routeclearance]",
	86:  "AT [position] EXPECT [routeclearance]",
	87:  "EXPECT DIRECT TO [position]",
	88:  "AT [position] EXPECT DIRECT TO [position]",
	89:  "AT [time] EXPECT DIRECT TO [position]",
	90:  "AT [altitude] EXPECT DIRECT TO [position]",
	91:  "HOLD AT [position] MAINTAIN [altitude] INBOUND TRACK [degrees] [direction] TURNS [legtype]",
	92:  "HOLD AT [position] AS PUBLISHED MAINTAIN [altitude]",
	93:  "EXPECT FURTHER CLEARANCE AT [time]",
	94:  "TURN [direction] HEADING [degrees]",
	95:  "TURN [direction] GROUND TRACK [degrees]",
	96:  "FLY PRESENT HEADING",
	97:  "AT [position] FLY HEADING [degrees]",
	98:  "IMMEDIATELY TURN [direction] HEADING [degrees]",
	99:  "EXPECT [procedurename]",
	100: "AT [time] EXPECT [speed]",
	101: "AT [position] EXPECT [speed]",
	102: "AT [altitude] EXPECT [speed]",
	103: "AT [time] EXPECT [speed] TO [speed]",
	104: "AT [position] EXPECT [speed] TO [speed]",
	105: "AT [altitude] EXPECT [speed] TO [speed]",
	106: "MAINTAIN [speed]",
	107: "MAINTAIN PRESENT SPEED",
	108: "MAINTAIN [speed] OR GREATER",
	109: "MAINTAIN [speed] OR LESS",
	110: "MAINTAIN [speed] TO [speed]",
	111: "INCREASE SPEED TO [speed]",
	112: "INCREASE SPEED TO [speed] OR GREATER",
	113: "REDUCE SPEED TO [speed]",
	114: "REDUCE SPEED TO [speed] OR LESS",
	115: "DO NOT EXCEED [speed]",
	116: "RESUME NORMAL SPEED",
	117: "CONTACT [icaounitname] [frequency]",
	118: "AT [position] CONTACT [icaounitname] [frequency]",
	119: "AT [time] CONTACT [icaounitname] [frequency]",
	120: "MONITOR [icaounitname] [frequency]",
	121: "AT [position] MONITOR [icaounitname] [frequency]",
	122: "AT [time] MONITOR [icaounitname] [frequency]",
	123: "SQUAWK [beaconcode]",
	124: "STOP SQUAWK",
	125: "SQUAWK ALTITUDE",
	126: "STOP ALTITUDE SQUAWK",
	127: "REPORT BACK ON ROUTE",
	128: "REPORT LEAVING [altitude]",
	129: "REPORT LEVEL [altitude]",
	130: "REPORT PASSING [position]",
	131: "REPORT REMAINING FUEL AND SOULS ON BOARD",
	132: "CONFIRM POSITION",
	133: "CONFIRM ALTITUDE",
	134: "CONFIRM SPEED",
	135: "CONFIRM ASSIGNED ALTITUDE",
	136: "CONFIRM ASSIGNED SPEED",
	137: "CONFIRM ASSIGNED ROUTE",
	138: "CONFIRM TIME OVER REPORTED WAYPOINT",
	139: "CONFIRM REPORTED WAYPOINT",
	140: "CONFIRM NEXT WAYPOINT",
	141: "CONFIRM NEXT WAYPOINT ETA",
	142: "CONFIRM ENSUING WAYPOINT",
	143: "CONFIRM REQUEST",
	144: "CONFIRM SQUAWK",
	145: "CONFIRM HEADING",
	146: "CONFIRM GROUND TRACK",
	147: "REQUEST POSITION REPORT",
	148: "WHEN CAN YOU ACCEPT [altitude]",
	149: "CAN YOU ACCEPT [altitude] AT [position]",
	150: "CAN YOU ACCEPT [altitude] AT [time]",
	151: "WHEN CAN YOU ACCEPT [speed]",
	152: "WHEN CAN YOU ACCEPT [distanceoffset] [direction] OFFSET",
	153: "ALTIMETER [altimeter]",
	154: "RADAR SERVICES TERMINATED",
	155: "RADAR CONTACT [position]",
	156: "RADAR CONTACT LOST",
	157: "CHECK STUCK MICROPHONE [frequency]",
	158: "ATIS [atiscode]",
	159: "ERROR [errorinformation]",
	160: "NEXT DATA AUTHORITY [icaofacilitydesignation]",
	161: "END SERVICE",
	162: "SERVICE UNAVAILABLE",
	163: "[icaofacilitydesignation] [tp4table]",
	164: "WHEN READY",
	165: "THEN",
	166: "DUE TO TRAFFIC",
	167: "DUE TO AIRSPACE RESTRICTION",
	168: "DISREGARD",
	169: "[freetext]",
	170: "[freetext]",
	171: "CLIMB AT [verticalrate] MINIMUM",
	172: "CLIMB AT [verticalrate] MAXIMUM",
	173: "DESCEND AT [verticalrate] MINIMUM",
	174: "DESCEND AT [verticalrate] MAXIMUM",
	175: "REPORT REACHING [altitude]",
	176: "MAINTAIN OWN SEPARATION AND VMC",
	177: "AT PILOTS DISCRETION",
	178: "(reserved)",
	179: "SQUAWK IDENT",
	180: "REPORT REACHING BLOCK [altitude] TO [altitude]",
	181: "REPORT DISTANCE [tofrom] [position]",
	182: "CONFIRM ATIS CODE",
}

// Downlink message labels (air to ground).
// These are pilot responses/requests to ATC.
var downlinkLabels = map[int]string{
	0:   "WILCO",
	1:   "UNABLE",
	2:   "STANDBY",
	3:   "ROGER",
	4:   "AFFIRM",
	5:   "NEGATIVE",
	6:   "REQUEST [altitude]",
	7:   "REQUEST BLOCK [altitude] TO [altitude]",
	8:   "REQUEST CRUISE CLIMB TO [altitude]",
	9:   "REQUEST CLIMB TO [altitude]",
	10:  "REQUEST DESCENT TO [altitude]",
	11:  "AT [position] REQUEST CLIMB TO [altitude]",
	12:  "AT [position] REQUEST DESCENT TO [altitude]",
	13:  "AT [time] REQUEST CLIMB TO [altitude]",
	14:  "AT [time] REQUEST DESCENT TO [altitude]",
	15:  "REQUEST OFFSET [distanceoffset] [direction] OF ROUTE",
	16:  "AT [position] REQUEST OFFSET [distanceoffset] [direction] OF ROUTE",
	17:  "AT [time] REQUEST OFFSET [distanceoffset] [direction] OF ROUTE",
	18:  "REQUEST [speed]",
	19:  "REQUEST [speed] TO [speed]",
	20:  "REQUEST VOICE CONTACT",
	21:  "REQUEST VOICE CONTACT [frequency]",
	22:  "REQUEST DIRECT TO [position]",
	23:  "REQUEST [procedurename]",
	24:  "REQUEST [routeclearance]",
	25:  "REQUEST CLEARANCE",
	26:  "REQUEST WEATHER DEVIATION TO [position] VIA [routeclearance]",
	27:  "REQUEST WEATHER DEVIATION UP TO [distanceoffset] [direction] OF ROUTE",
	28:  "LEAVING [altitude]",
	29:  "CLIMBING TO [altitude]",
	30:  "DESCENDING TO [altitude]",
	31:  "PASSING [position]",
	32:  "PRESENT ALTITUDE [altitude]",
	33:  "PRESENT POSITION [position]",
	34:  "PRESENT SPEED [speed]",
	35:  "PRESENT HEADING [degrees]",
	36:  "PRESENT GROUND TRACK [degrees]",
	37:  "LEVEL [altitude]",
	38:  "ASSIGNED ALTITUDE [altitude]",
	39:  "ASSIGNED SPEED [speed]",
	40:  "ASSIGNED ROUTE [routeclearance]",
	41:  "BACK ON ROUTE",
	42:  "NEXT WAYPOINT [position]",
	43:  "NEXT WAYPOINT ETA [time]",
	44:  "ENSUING WAYPOINT [position]",
	45:  "REPORTED WAYPOINT [position]",
	46:  "REPORTED WAYPOINT [time]",
	47:  "SQUAWKING [beaconcode]",
	48:  "POSITION REPORT [positionreport]",
	49:  "WHEN CAN WE EXPECT [speed]",
	50:  "WHEN CAN WE EXPECT [speed] TO [speed]",
	51:  "WHEN CAN WE EXPECT BACK ON ROUTE",
	52:  "WHEN CAN WE EXPECT LOWER ALTITUDE",
	53:  "WHEN CAN WE EXPECT HIGHER ALTITUDE",
	54:  "WHEN CAN WE EXPECT CRUISE CLIMB TO [altitude]",
	55:  "PAN PAN PAN",
	56:  "MAYDAY MAYDAY MAYDAY",
	57:  "[remainingfuel] OF FUEL REMAINING AND [remainingsouls] SOULS ON BOARD",
	58:  "CANCEL EMERGENCY",
	59:  "DIVERTING TO [position] VIA [routeclearance]",
	60:  "OFFSETTING [distanceoffset] [direction] OF ROUTE",
	61:  "DESCENDING TO [altitude]",
	62:  "ERROR [errorinformation]",
	63:  "NOT CURRENT DATA AUTHORITY",
	64:  "[icaofacilitydesignation]",
	65:  "DUE TO WEATHER",
	66:  "DUE TO AIRCRAFT PERFORMANCE",
	67:  "[freetext]",
	68:  "[freetext]",
	69:  "REQUEST VMC DESCENT",
	70:  "REQUEST HEADING [degrees]",
	71:  "REQUEST GROUND TRACK [degrees]",
	72:  "REACHING [altitude]",
	73:  "[versionnumber]",
	74:  "MAINTAIN OWN SEPARATION AND VMC",
	75:  "AT PILOTS DISCRETION",
	76:  "REACHING BLOCK [altitude] TO [altitude]",
	77:  "ASSIGNED BLOCK [altitude] TO [altitude]",
	78:  "AT [time] [distance] [tofrom] [position]",
	79:  "ATIS [atiscode]",
	80:  "DEVIATING [distanceoffset] [direction] OF ROUTE",
}

// GetUplinkLabel returns the label template for an uplink message ID.
func GetUplinkLabel(msgID int) string {
	if label, ok := uplinkLabels[msgID]; ok {
		return label
	}
	return "(reserved)"
}

// GetDownlinkLabel returns the label template for a downlink message ID.
func GetDownlinkLabel(msgID int) string {
	if label, ok := downlinkLabels[msgID]; ok {
		return label
	}
	return "(reserved)"
}
